### ISSUE TITLE
20.20.16837 fails to build on IA32

### ISSUE THREAD

**Issue by jbeich** [intel/compute-runtime#316]
Regressed by 4216e962b24d.

Clang 10:
```c++
shared/source/os_interface/linux/drm_memory_manager.cpp:61:54: error: non-const
      lvalue reference to type 'size_t' (aka 'unsigned int') cannot bind to a value of unrelated type 'uint64_t'
      (aka 'unsigned long long')
                    bo->gpuAddress = acquireGpuRange(bo->size, false, rootDeviceIndex, false);
                                                     ^~~~~~~~
shared/source/os_interface/linux/drm_memory_manager.h:66:38: note: passing argument
      to parameter 'size' here
    uint64_t acquireGpuRange(size_t &size, bool requireSpecificBitness, uint32_t rootDeviceIndex, bool requi...
                                     ^
```
GCC 9:
```c++
shared/source/os_interface/linux/drm_memory_manager.cpp: In constructor 'NEO::DrmMemoryManager::DrmMemoryManager(NEO::gemCloseWorkerMode, bool, bool, NEO::ExecutionEnvironment&)':
shared/source/os_interface/linux/drm_memory_manager.cpp:61:58: error: cannot bind non-const lvalue reference of type 'size_t&' {aka 'unsigned int&'} to an rvalue of type 'size_t' {aka 'unsigned int'}
   61 |                     bo->gpuAddress = acquireGpuRange(bo->size, false, rootDeviceIndex, false);
      |                                                      ~~~~^~~~
In file included from shared/source/os_interface/linux/drm_memory_manager.cpp:8:
shared/source/os_interface/linux/drm_memory_manager.h:66:38: note:   initializing argument 1 of 'uint64_t NEO::DrmMemoryManager::acquireGpuRange(size_t&, bool, uint32_t, bool)'
   66 |     uint64_t acquireGpuRange(size_t &size, bool requireSpecificBitness, uint32_t rootDeviceIndex, bool requiresStandard64KBHeap);
      |                              ~~~~~~~~^~~~
```

**Comment by JacekDanecki** [comment]
Neo doesn't support 32 bits arch under Linux. Closing issue.
